### ISSUE TITLE
Create Icons and Logo

### ISSUE THREAD

**Issue by berndulum** [gody01/ecovent_v2#10]
Hi, I noticed that there are no icons and logos for this integration available. Therefore in different place in HA (e.g. overview of integrations and overview of devices) only free space is displayed. New icons can be submitted to this repo: https://github.com/home-assistant/brands

I am thinking of creating an icon and logo for this integration by using the Blauberg logo: https://blaubergventilatoren.de/assets/9f5a0cb2/images/blauberg.svg

What do you think? I only want to do it if this is fine for the author of this integration.

**Comment by gody01** [comment]
It is fine by me. Go for it.
I just have to mention, that I'm in no way connected with Blauberg, so I have no clue about copyrights of the logo ...

**Comment by berndulum** [comment]
Thanks, I created the PR for the brands repo: https://github.com/home-assistant/brands/pull/4150

**Comment by berndulum** [comment]
The PR was merged and the icon and logo are now automatically used in home assistant. Therefore I close this topic.

Example in the integration overview:
![image](https://user-images.githubusercontent.com/14736709/222801530-94211b48-a717-4fca-8528-e571ff1b6e7b.png)

Or in the device details:
![image](https://user-images.githubusercontent.com/14736709/222801727-1defc585-fec4-487e-9c4e-13e485ad1cb6.png)
