### ISSUE TITLE
VENTO Expert A50-1 W v1

### ISSUE THREAD

**Issue by kondrikserg** [gody01/ecovent_v2#7]
will this component work with version 1 ? Is it planned to improve support for VENTO Expert A50-1 W v1 ?

https://blaubergventilatoren.de/uploads/download/ventoexpertduowsmarthousev11en.pdf

**Comment by gody01** [comment]
Sorry, I don't have access tro v1 variatns so I can't integrate.
There is original v1 integration:
https://github.com/aglehmann/home_assistant_ecovent
