### ISSUE TITLE
Slave device 

### ISSUE THREAD

**Issue by karloslb** [gody01/ecovent_v2#8]
Hi,
first of all thank you for your great work.

I would be very happy if the slave device could be control.
e.g turn on/off.
Why: if the window is open in the room with the slave device, the slave device does not have to be on.

**Comment by gody01** [comment]
Hello,

Slave devices can't be controlled via Wi-Fi it seems (firmware functionality).

I have all my fans in master mode, and paired them as groups in HomeAssistant for simmilar behavour as Master/Slave.

**Comment by karloslb** [comment]
ok, 
ok, but how do you sync both devices? E.g. if I turn on both devices at the same time, it may be that they work against each other

**Comment by gody01** [comment]
Default direction of device is determined by hardware switch position.
Master and slave have to have different setting anyway.

Then, when You turn group on fans start with default direction.

My fans, seems to maintain correct behavior...

However, to get preset modes on group, You have to define it as "old style groups"  https://www.home-assistant.io/integrations/group/

One of my group is in groups.yaml file defined like that:

fans_east:
    name: Vento East
    all: true
    entities:
        - fan.livingroom_fan
        - fan.bedroom_fan

**Comment by karloslb** [comment]
thank you,
it actually works as you described. I have tested it.

**Comment by karloslb** [comment]
I have still one question:
why group fan3 doesn't support preset_mode? 
I created the group as a FAN group.
![grafik](https://user-images.githubusercontent.com/118773569/210659224-9b7890fd-921a-4819-ada9-dfcdf39ad52f.png)

**Comment by gody01** [comment]
Did Yiu create group via UI or as platform group ?
Preset modes are not implemented for fan group platform.

As mentioned above. To have preset_modes available, You have to define groups as "old style groups" in yaml (best place in file groups.yaml) as:

fans_east:
   name: Vento East
   all: true
   entities:
        - fan.livingroom_fan
        - fan.bedroom_fan

**Comment by gody01** [comment]
Editor removes spaces, so You need to format correctly for yaml syntax.

**Comment by karloslb** [comment]
I created a group as you described:
configuration.yaml
![grafik](https://user-images.githubusercontent.com/118773569/210892663-5e1c722b-7c88-4e29-8a43-6e88b98e5571.png)
Unfortunately, the Preset mode is still not available:

**Comment by gody01** [comment]
No. This is new style of group with platform: group

in file /config/groups.yaml write something like this:

`fans_test:
    name: Test fan group
    all: true
    entities:
        - fan.fan1
        - fan.fan2`

This is in documentation about group "https://www.home-assistant.io/integrations/group/" described as "Old style groups", not recomended but still usable.

This style of groups are for UI only and does not get properties of the members like new style groups.
But preset mode for fan groups are working with this "Old style groups", so for time being until fan groups gets preset support this is only option to set preset on fan groups.

**Comment by karloslb** [comment]
![grafik](https://user-images.githubusercontent.com/118773569/210904084-76b552d6-34d5-4a88-a51e-e06fd6121e04.png)
![grafik](https://user-images.githubusercontent.com/118773569/210904117-c4708f23-f655-4292-ae7f-cfac362bb0c5.png)
![grafik](https://user-images.githubusercontent.com/118773569/210904192-1738c28f-ec97-46bd-a1d4-d074915ba1d4.png)

**Comment by gody01** [comment]
From docs:

Back in the day, Home Assistant used groups to visually groups entities in the Home Assistant UI; it was the only way to tell which entities would show up in a single card on your Dashboard. This is no longer the case, as we now have fantastic UI editors and Dashboarding.

However, the old-style groups are still there in the roots of Home Assistant. On the one hand, they are more versatile (they can use more entity types right now); but on the other hand, they are also more limited and complicated to use.

==============================================================================================
To use this group entity, you have to put it in a card on dashoard. They don't "inherit" properties of members, like new style groups.


![image](https://user-images.githubusercontent.com/3974636/210955537-a26c0c81-68c2-4779-945c-064ccffd14aa.png)

**Comment by karloslb** [comment]
thank you for your support and your patience. It was important to me that the group works in automation and it does. I have to edit the action manually.
![grafik](https://user-images.githubusercontent.com/118773569/210974578-7472f00c-08d8-45bd-9ef3-aa65baf6e48d.png)

 I didn't know that before.
